name: Generate Index File

on:
  push:
    branches: [main]
    paths:
      - 'wau-mods/**/*'

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Index File
        run: |
          index_content=""
          for file in $(find wau-mods -type f); do
            filename=$(basename "$file")
            index_content+="<li><a href=\"$filename\">$filename</a></li>\n"
          done

          echo "<ul>$index_content</ul>" > wau-mods/index.html

      - name: Commit Index File
        run: |
          git add wau-mods/index.html
          git commit -m "Updated index.html"
          git push origin main
