name: Generate Index.html

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate index.html
        run: |
          git config --global user.email "d.fawdon@uea.ac.uk"
          git config --global user.name "DF-UEA"
          directory='wau-mods'

          # Create a list of files in the directory
          files=$(find "wau-mods" -type f)

          # Generate the index.html content
          html_content="<ul>"
          for file in $files; do
            html_content+="<li><a href='$file'>$file</a></li>"
          done
          html_content+="</ul>"

          # Write the index.html content to a file
          echo "$html_content" > "wau-mods/index.html"

      - name: Commit index.html
        run: |
          git add "wau-mods/index.html"
          git commit -m "Updated index.html"
          git push origin main
